name: SLSA go releaser
on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    tags:
      - "*"

permissions: read-all

jobs:
  args:
    runs-on: macOS-12
    steps:
      - id: checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # tag=v2.3.4
        with:
          fetch-depth: 0

  # Trusted builder.
  build:
    permissions:
      id-token: write # To sign the provenance.
      contents: write # To upload assets to release.
      actions: read # To read the workflow path.
    needs: args
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.2.2
    with:
      go-version: 1.18
